name: On Push

on: 
  release:
    types: 
      - published

jobs:
  publish_to_twitter:
    runs-on: ubuntu-latest
    steps:
      - name: Posting To Twitter
        uses: m1ner79/Github-Twittction@master
        with:
          twitter_status: |
            📢 New Version ${{github.event.release.tag_name}} 🎉 is available

            ${{github.event.release.html_url}}

            #wordpress #wpplugins #wpthemes #wpframework #wordpressplugin #wordpressframework #wp #framework #library
          twitter_consumer_key: ${{ secrets.TWITTER_API_KEY }} 
          twitter_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }} 
          twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
          twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Contents
        uses: actions/checkout@v2    
      - name: Updating Change-Log
        uses: varunsridharan/action-change-log-updater@master
        with:
          REPO_NAME: "wponion/docs"
          REMOTE_FILE: "others/change-log.md"
          LOCAL_FILE: "CHANGELOG.md"
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          
  upload_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Contents
        uses: actions/checkout@v2   
      - name: Installing Composer
        uses: nanasess/composer-installer-action@master
      - name: Create Github Release Archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir dist/
          composer install --no-dev && git archive -o dist/"$VERSION.zip"  HEAD && zip -gr dist/"$VERSION.zip" vendor/
      - name: Upload To Github
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  #upload_demo:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Fetching Contents
  #    uses: actions/checkout@v2
  #  - name: Installing Composer
  #    uses: pxgamer/composer-action@master
  #    with:
  #      command: install --no-dev
  #  - name: Uploading To FTP
  #    uses: SamKirkland/FTP-Deploy-Action@3.1.0
  #    with:
  #      ftp-server: ${{ secrets.FTP_HOST }}
  #      ftp-username: ${{ secrets.FTP_USERNAME }}
  #      ftp-password: ${{ secrets.FTP_PASSWORD }}
